# Use postgres/example user/password credentials
version: "3.7"

services:

  forum-db:
    container_name: forum-db-dev
    build:
      context: ./
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: server
      PGDATA: /data/pgdata
    volumes:
      - ./dev:/data/pgdata
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/1-schema.sql
    ports:
      - "5432:5432"
